### Obtener todos los clientes
GET http://localhost:3000/api/clientes

### Obtener un cliente por ID
GET http://localhost:3000/api/clientes/1

### Crear un nuevo cliente
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "razonSocial": "XTZ Insumos",
  "cuit": "30123456789",
  "tel": "345096721",
  "email": "insumos_xtz@gmail.com"
}

### Actualizar un cliente existente
PUT http://localhost:3000/api/clientes/1
Content-Type: application/json

{
  "razonSocial": "Empresa MZ",
  "cuit": "35555555553",
  "tel": "3451234987",
  "email": "email@empresamz.com"
}

### Eliminar un cliente
DELETE http://localhost:3000/api/clientes/1