### obtener todos los clientes
GET http://localhost:3000/api/clientes

### obtener un cliente por ID
GET http://localhost:3000/api/clientes/1

### crear un nuevo cliente
POST http://localhost:3000/api/clientes 
Content-Type: application/json

{
  "razon_social": "Empresa XYZ",
  "cuit": "30-12345678-9",
  "tel": 123456789,
  "email": "email@empresaxyz.com"
}

### actualizar un cliente existente
PUT http://localhost:3000/api/clientes/2
Content-Type: application/json

{
  "razon_social": "Empresa MZ",
  "cuit": "35-55555555-3",
  "tel": 987987987,
  "email": "email@empresamz.com"
}


### actualizar parcialmente un cliente existente
PATCH http://localhost:3000/api/clientes/2
Content-Type: application/json

{
  "tel": 888888888
}

### eliminar un cliente
DELETE http://localhost:3000/api/clientes/2